# # Generated by Django 5.0.7 on 2024-12-04 17:38
#
# from django.db import migrations
#
#
# class Migration(migrations.Migration):
#
#     dependencies = [
#     ]
#
#     operations = [
#     ]
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        # Dependencies go here
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('details', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=models.CASCADE, to='auth.User')),  # String reference to User
            ],
        ),
    ]
