# Generated by Django 5.0.7 on 2024-12-04 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_post_alter_box_id_alter_box_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
