# Generated by Django 5.0.7 on 2024-12-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0003_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='user',
        ),
    ]
